/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary': '#4edea3',
        'primary-dim': '#2db882',
        'on-primary': '#003824',
        'primary-container': '#10b981',
        'secondary': '#4fdbc8',
        'on-secondary': '#003731',
        'tertiary': '#4cd7f6',
        'surface': '#0e1511',
        'surface-dim': '#0e1511',
        'surface-container-lowest': '#09100c',
        'surface-container-low': '#161d19',
        'surface-container': '#1a211d',
        'surface-container-high': '#242c27',
        'surface-container-highest': '#2f3632',
        'surface-variant': '#2f3632',
        'surface-bright': '#343b36',
        'on-surface': '#dde4dd',
        'on-surface-variant': '#bbcabf',
        'outline': '#86948a',
        'outline-variant': '#3c4a42',
        'error': '#ffb4ab',
        'error-container': '#93000a',
        'background': '#0e1511',
        'on-background': '#dde4dd',
        'inverse-surface': '#dde4dd',
        'inverse-on-surface': '#2b322d',
        'inverse-primary': '#006c49',
        'surface-tint': '#4edea3',
      },
      fontFamily: {
        sans: ['Geist', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'display': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-mono': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '500' }],
      },
      animation: {
        'bg-shift': 'bg-shift 18s ease infinite',
        'pulse-border': 'pulse-border 3s cubic-bezier(0.4,0,0.6,1) infinite',
        'float': 'float 5s ease-in-out infinite',
        'waveform': 'waveform 1.2s ease-in-out infinite alternate',
        'shimmer': 'shimmer 2s linear infinite',
        'spin-slow': 'spin 8s linear infinite',
        'fade-in': 'fade-in 0.4s ease forwards',
        'slide-up': 'slide-up 0.4s ease forwards',
      },
      keyframes: {
        'bg-shift': { '0%': { backgroundPosition: '0% 50%' }, '50%': { backgroundPosition: '100% 50%' }, '100%': { backgroundPosition: '0% 50%' } },
        'pulse-border': { '0%,100%': { opacity: '1', borderColor: '#3c4a42' }, '50%': { opacity: '0.5', borderColor: '#4edea3' } },
        'float': { '0%,100%': { transform: 'translateY(0)' }, '50%': { transform: 'translateY(-8px)' } },
        'waveform': { '0%': { height: '4px' }, '100%': { height: '100%' } },
        'shimmer': { '0%': { backgroundPosition: '-200% 0' }, '100%': { backgroundPosition: '200% 0' } },
        'fade-in': { '0%': { opacity: '0' }, '100%': { opacity: '1' } },
        'slide-up': { '0%': { opacity: '0', transform: 'translateY(12px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
      },
    },
  },
  plugins: [],
}
